install-django:
	pip install django

startproject:
	python -m django startproject library

runserver:
	python manage.py runserver

startapp:
	python manage.py startapp catalog

makemigrations:
	python manage.py makemigrations

migrate:
	python manage.py migrate

createsuperuser:
	python manage.py createsuperuser

fill_db:
	python manage.py fill_db